version: "3"

services:
  backend:
    container_name: phone_shop
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    environment:
      DB_URL: jdbc:postgresql://postgresql:5432/postgres
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      shop.jwt.secret.access: M+9HLgODaHfqzPmg1IRQw+0R80q98WqwqrNysheVBy/fwSE2MaIlZ4fm74rrEbtX5n9cUf6GbGj/+deFKiDrDg==
      shop.jwt.secret.refresh: JkTtZdCbDJgE4ssjHV1bo8JACKTc6NybAGvHv4Cw5BnfhM3H8gp3736txkW1ZLG5ygUaxy2gCDkWw1rhYIR3DQ==
      shop.jwt.expires.access-sec: 604800
      shop.jwt.expires.refresh-days: 30
    volumes:
      - /var/log/phone_shop:/logs

  postgresql:
    container_name: phone_shop_db
    image: "postgres:14.2"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: phone_shop_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
