version: "3"

services:
  backend:
    container_name: phone_shop
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    environment:
      DB_URL: postgresql://postgresql:5432/postgres
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    volumes:
      - /var/log/phone_shop:/logs

  postgresql:
    container_name: phone_shop_db
    image: "postgres:14.2"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: phone_shop_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
