server:
  forward-headers-strategy: native
  port: 8080
  error:
    include-message: always

spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'

  datasource:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    baseline-on-migrate: true
    locations: 'classpath:db.migration'
    schemas: 'public'
    enabled: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springfox:
  documentation:
    swagger:
      v2:
        use-model-v3: false

shop:
  jwt:
    secret:
      access: ${JWT_ACCESS_SECRET}
      refresh: ${JWT_REFRESH_SECRET}
    expires:
      access-sec: 604800
      refresh-days: 30
