alter table if exists refresh_token drop constraint if exists fk_user_id;
alter table if exists subcategory drop constraint if exists fk_category_id;
alter table if exists product drop constraint if exists fk_subcategory_id;
alter table if exists user_product drop constraint if exists fk_product_id;
alter table if exists user_product drop constraint if exists fk_user_id;

drop table if exists "user" cascade;
drop table if exists category cascade;
drop table if exists refresh_token cascade;
drop table if exists subcategory cascade;
drop table if exists product cascade;
drop table if exists user_product cascade;

create table "user"
(
    user_id bigint generated by default as identity,
    first_name varchar(255) not null,
    last_name varchar(255) not null,
    email varchar(255) not null,
    password varchar(255) not null,
    primary key (user_id)
);

create table product
(
    product_id bigint generated by default as identity,
    title varchar(255) not null,
    description varchar(500) not null,
    amount bigint not null,
    picture_url varchar(255) not null,
    price bigint not null,
    discount_price bigint,
    discount boolean not null,
    subcategory_id bigint not null,
    primary key (product_id)
);

create table user_product
(
    user_product_id bigint generated by default as identity,
    user_id bigint not null,
    product_id bigint not null,
    amount bigint not null,
    primary key (user_product_id)
);

create table subcategory
(
    subcategory_id bigint generated by default as identity,
    category_id bigint not null,
    title varchar(255) not null,
    primary key (subcategory_id)
);

create table category
(
    category_id bigint generated by default as identity,
    title varchar(255) not null,
    primary key (category_id)
);

create table refresh_token
(
    token_id bigint generated by default as identity,
    token varchar(255) not null,
    user_id bigint not null,
    primary key (token_id)
);

alter table if exists user_product add constraint fk_product_id foreign key (product_id) references product;
alter table if exists user_product add constraint fk_user_id foreign key (user_id) references "user";
alter table if exists subcategory add constraint fk_category_id foreign key (category_id) references category;
alter table if exists product add constraint fk_subcategory_id foreign key (subcategory_id) references subcategory;
alter table refresh_token add constraint fk_user_id foreign key (user_id) references "user";
